[theme]
base = "light"
primaryColor = "#1664D9"
backgroundColor = "#F6F8FB"
secondaryBackgroundColor = "#EEF2F7"
textColor = "#1B2433"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
